'use client';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReduxProvider from "./providers/ReduxProvider";
import MobileBubbleNav from "./components/MobileBubbleNav";
import Navbar from "./ui/NavBar";
import { StoreProvider } from "./store/StoreContext";
import { useEffect, useState } from "react";
import IntroLoader from "./components/loading/IntroLoader";
import Footer from "./ui/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const timer = setTimeout(() => setLoading(false), 1800); // adjust duration
    return () => clearTimeout(timer);
  }, []);

  return (
    <html lang="en">
      {/* Prevent theme flash by setting class before paint */}
      <script
        dangerouslySetInnerHTML={{
          __html: `(()=>{try{const t=localStorage.getItem("theme");const m=window.matchMedia&&window.matchMedia("(prefers-color-scheme: dark)").matches;const dark=t?t==="dark":m;const r=document.documentElement;r.classList.remove("theme-dark","theme-light");r.classList.add(dark?"theme-dark":"theme-light");}catch{}})();`,
        }}
      />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          <StoreProvider>
            {
              loading && <IntroLoader/> 
            }
                    <MobileBubbleNav />

                    <Navbar />
            
            {children}
                  <Footer />
            
          </StoreProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
